package com.shopsthai.david.hibernate;

// Generated Nov 14, 2013 10:42:18 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Armas generated by hbm2java
 */
public class Armas implements java.io.Serializable {

	private String cuscod;
	private String custyp;
	private String prenam;
	private String cusnam;
	private String addr01;
	private String addr02;
	private String addr03;
	private String zipcod;
	private String telnum;
	private String contact;
	private String cusnam2;
	private String taxid;
	private String taxtyp;
	private Double taxrat;
	private String taxgrp;
	private String taxcond;
	private String shipto;
	private String slmcod;
	private String areacod;
	private Integer paytrm;
	private String paycond;
	private String payer;
	private String tabpr;
	private String disc;
	private Double balance;
	private Double chqrcv;
	private Double crline;
	private Date lasivc;
	private String accnum;
	private String remark;
	private String dlvby;
	private String tracksal;
	private String creby;
	private Date credat;
	private String userid;
	private Date chgdat;
	private String status;
	private Date inactdat;

	public Armas() {
	}

	public Armas(String cuscod) {
		this.cuscod = cuscod;
	}

	public Armas(String cuscod, String custyp, String prenam, String cusnam,
			String addr01, String addr02, String addr03, String zipcod,
			String telnum, String contact, String cusnam2, String taxid,
			String taxtyp, Double taxrat, String taxgrp, String taxcond,
			String shipto, String slmcod, String areacod, Integer paytrm,
			String paycond, String payer, String tabpr, String disc,
			Double balance, Double chqrcv, Double crline, Date lasivc,
			String accnum, String remark, String dlvby, String tracksal,
			String creby, Date credat, String userid, Date chgdat,
			String status, Date inactdat) {
		this.cuscod = cuscod;
		this.custyp = custyp;
		this.prenam = prenam;
		this.cusnam = cusnam;
		this.addr01 = addr01;
		this.addr02 = addr02;
		this.addr03 = addr03;
		this.zipcod = zipcod;
		this.telnum = telnum;
		this.contact = contact;
		this.cusnam2 = cusnam2;
		this.taxid = taxid;
		this.taxtyp = taxtyp;
		this.taxrat = taxrat;
		this.taxgrp = taxgrp;
		this.taxcond = taxcond;
		this.shipto = shipto;
		this.slmcod = slmcod;
		this.areacod = areacod;
		this.paytrm = paytrm;
		this.paycond = paycond;
		this.payer = payer;
		this.tabpr = tabpr;
		this.disc = disc;
		this.balance = balance;
		this.chqrcv = chqrcv;
		this.crline = crline;
		this.lasivc = lasivc;
		this.accnum = accnum;
		this.remark = remark;
		this.dlvby = dlvby;
		this.tracksal = tracksal;
		this.creby = creby;
		this.credat = credat;
		this.userid = userid;
		this.chgdat = chgdat;
		this.status = status;
		this.inactdat = inactdat;
	}

	public String getCuscod() {
		return this.cuscod;
	}

	public void setCuscod(String cuscod) {
		this.cuscod = cuscod;
	}

	public String getCustyp() {
		return this.custyp;
	}

	public void setCustyp(String custyp) {
		this.custyp = custyp;
	}

	public String getPrenam() {
		return this.prenam;
	}

	public void setPrenam(String prenam) {
		this.prenam = prenam;
	}

	public String getCusnam() {
		return this.cusnam;
	}

	public void setCusnam(String cusnam) {
		this.cusnam = cusnam;
	}

	public String getAddr01() {
		return this.addr01;
	}

	public void setAddr01(String addr01) {
		this.addr01 = addr01;
	}

	public String getAddr02() {
		return this.addr02;
	}

	public void setAddr02(String addr02) {
		this.addr02 = addr02;
	}

	public String getAddr03() {
		return this.addr03;
	}

	public void setAddr03(String addr03) {
		this.addr03 = addr03;
	}

	public String getZipcod() {
		return this.zipcod;
	}

	public void setZipcod(String zipcod) {
		this.zipcod = zipcod;
	}

	public String getTelnum() {
		return this.telnum;
	}

	public void setTelnum(String telnum) {
		this.telnum = telnum;
	}

	public String getContact() {
		return this.contact;
	}

	public void setContact(String contact) {
		this.contact = contact;
	}

	public String getCusnam2() {
		return this.cusnam2;
	}

	public void setCusnam2(String cusnam2) {
		this.cusnam2 = cusnam2;
	}

	public String getTaxid() {
		return this.taxid;
	}

	public void setTaxid(String taxid) {
		this.taxid = taxid;
	}

	public String getTaxtyp() {
		return this.taxtyp;
	}

	public void setTaxtyp(String taxtyp) {
		this.taxtyp = taxtyp;
	}

	public Double getTaxrat() {
		return this.taxrat;
	}

	public void setTaxrat(Double taxrat) {
		this.taxrat = taxrat;
	}

	public String getTaxgrp() {
		return this.taxgrp;
	}

	public void setTaxgrp(String taxgrp) {
		this.taxgrp = taxgrp;
	}

	public String getTaxcond() {
		return this.taxcond;
	}

	public void setTaxcond(String taxcond) {
		this.taxcond = taxcond;
	}

	public String getShipto() {
		return this.shipto;
	}

	public void setShipto(String shipto) {
		this.shipto = shipto;
	}

	public String getSlmcod() {
		return this.slmcod;
	}

	public void setSlmcod(String slmcod) {
		this.slmcod = slmcod;
	}

	public String getAreacod() {
		return this.areacod;
	}

	public void setAreacod(String areacod) {
		this.areacod = areacod;
	}

	public Integer getPaytrm() {
		return this.paytrm;
	}

	public void setPaytrm(Integer paytrm) {
		this.paytrm = paytrm;
	}

	public String getPaycond() {
		return this.paycond;
	}

	public void setPaycond(String paycond) {
		this.paycond = paycond;
	}

	public String getPayer() {
		return this.payer;
	}

	public void setPayer(String payer) {
		this.payer = payer;
	}

	public String getTabpr() {
		return this.tabpr;
	}

	public void setTabpr(String tabpr) {
		this.tabpr = tabpr;
	}

	public String getDisc() {
		return this.disc;
	}

	public void setDisc(String disc) {
		this.disc = disc;
	}

	public Double getBalance() {
		return this.balance;
	}

	public void setBalance(Double balance) {
		this.balance = balance;
	}

	public Double getChqrcv() {
		return this.chqrcv;
	}

	public void setChqrcv(Double chqrcv) {
		this.chqrcv = chqrcv;
	}

	public Double getCrline() {
		return this.crline;
	}

	public void setCrline(Double crline) {
		this.crline = crline;
	}

	public Date getLasivc() {
		return this.lasivc;
	}

	public void setLasivc(Date lasivc) {
		this.lasivc = lasivc;
	}

	public String getAccnum() {
		return this.accnum;
	}

	public void setAccnum(String accnum) {
		this.accnum = accnum;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getDlvby() {
		return this.dlvby;
	}

	public void setDlvby(String dlvby) {
		this.dlvby = dlvby;
	}

	public String getTracksal() {
		return this.tracksal;
	}

	public void setTracksal(String tracksal) {
		this.tracksal = tracksal;
	}

	public String getCreby() {
		return this.creby;
	}

	public void setCreby(String creby) {
		this.creby = creby;
	}

	public Date getCredat() {
		return this.credat;
	}

	public void setCredat(Date credat) {
		this.credat = credat;
	}

	public String getUserid() {
		return this.userid;
	}

	public void setUserid(String userid) {
		this.userid = userid;
	}

	public Date getChgdat() {
		return this.chgdat;
	}

	public void setChgdat(Date chgdat) {
		this.chgdat = chgdat;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Date getInactdat() {
		return this.inactdat;
	}

	public void setInactdat(Date inactdat) {
		this.inactdat = inactdat;
	}

}
