package com.shopsthai.david.hibernate;

// Generated Nov 14, 2013 10:42:18 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Reply generated by hbm2java
 */
public class Reply implements java.io.Serializable {

	private Long replyNo;
	private long commentNo;
	private String userId;
	private String replyContent;
	private Date regDate;

	public Reply() {
	}

	public Reply(long commentNo, String userId, String replyContent,
			Date regDate) {
		this.commentNo = commentNo;
		this.userId = userId;
		this.replyContent = replyContent;
		this.regDate = regDate;
	}

	public Long getReplyNo() {
		return this.replyNo;
	}

	public void setReplyNo(Long replyNo) {
		this.replyNo = replyNo;
	}

	public long getCommentNo() {
		return this.commentNo;
	}

	public void setCommentNo(long commentNo) {
		this.commentNo = commentNo;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getReplyContent() {
		return this.replyContent;
	}

	public void setReplyContent(String replyContent) {
		this.replyContent = replyContent;
	}

	public Date getRegDate() {
		return this.regDate;
	}

	public void setRegDate(Date regDate) {
		this.regDate = regDate;
	}

}
