package com.shopsthai.david.hibernate;

// Generated Nov 14, 2013 10:42:18 PM by Hibernate Tools 3.4.0.CR1

/**
 * Tbnode generated by hbm2java
 */
public class Tbnode implements java.io.Serializable {

	private int idx;
	private String label;
	private String type;
	private String groupName;
	private String p;
	private Integer parentid;
	private String toggled;
	private String haveChild;

	public Tbnode() {
	}

	public Tbnode(int idx) {
		this.idx = idx;
	}

	public Tbnode(int idx, String label, String type, String groupName,
			String p, Integer parentid, String toggled, String haveChild) {
		this.idx = idx;
		this.label = label;
		this.type = type;
		this.groupName = groupName;
		this.p = p;
		this.parentid = parentid;
		this.toggled = toggled;
		this.haveChild = haveChild;
	}

	public int getIdx() {
		return this.idx;
	}

	public void setIdx(int idx) {
		this.idx = idx;
	}

	public String getLabel() {
		return this.label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getGroupName() {
		return this.groupName;
	}

	public void setGroupName(String groupName) {
		this.groupName = groupName;
	}

	public String getP() {
		return this.p;
	}

	public void setP(String p) {
		this.p = p;
	}

	public Integer getParentid() {
		return this.parentid;
	}

	public void setParentid(Integer parentid) {
		this.parentid = parentid;
	}

	public String getToggled() {
		return this.toggled;
	}

	public void setToggled(String toggled) {
		this.toggled = toggled;
	}

	public String getHaveChild() {
		return this.haveChild;
	}

	public void setHaveChild(String haveChild) {
		this.haveChild = haveChild;
	}

}
