package com.shopsthai.david.hibernate;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Transient;

// Generated Nov 14, 2013 10:42:18 PM by Hibernate Tools 3.4.0.CR1

/**
 * Cafolder generated by hbm2java
 */
public class Cafolder implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6464715017592020871L;
	private Integer idx;
	private String name;
	private String label;
	private String description;
	private Integer parentid;
	private String isBranch;
	private String state;
	private String isOpen;
	
	@Transient
	private List<Cafolder> children = new ArrayList<Cafolder>();
	

	public Cafolder() {
	}

	public Cafolder(String name) {
		this.name = name;
	}

	public Cafolder(String name, String label, String description,
			Integer parentid, String isBranch, String state, String isOpen) {
		this.name = name;
		this.label = label;
		this.description = description;
		this.parentid = parentid;
		this.isBranch = isBranch;
		this.state = state;
		this.isOpen = isOpen;
	}

	public Integer getIdx() {
		return this.idx;
	}

	public void setIdx(Integer idx) {
		this.idx = idx;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getLabel() {
		return this.label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Integer getParentid() {
		return this.parentid;
	}

	public void setParentid(Integer parentid) {
		this.parentid = parentid;
	}

	public String getIsBranch() {
		return this.isBranch;
	}

	public void setIsBranch(String isBranch) {
		this.isBranch = isBranch;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getIsOpen() {
		return this.isOpen;
	}

	public void setIsOpen(String isOpen) {
		this.isOpen = isOpen;
	}

	public List<Cafolder> getChildren() {
		return children;
	}

	public void setChildren(List<Cafolder> children) {
		this.children = children;
	}

}
