package com.shopsthai.david.hibernate;

// Generated Nov 14, 2013 10:42:18 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * EmpOrgchart generated by hbm2java
 */
public class EmpOrgchart implements java.io.Serializable {

	private String emp;
	private String boss;
	private BigDecimal salery;

	public EmpOrgchart() {
	}

	public EmpOrgchart(String emp, BigDecimal salery) {
		this.emp = emp;
		this.salery = salery;
	}

	public EmpOrgchart(String emp, String boss, BigDecimal salery) {
		this.emp = emp;
		this.boss = boss;
		this.salery = salery;
	}

	public String getEmp() {
		return this.emp;
	}

	public void setEmp(String emp) {
		this.emp = emp;
	}

	public String getBoss() {
		return this.boss;
	}

	public void setBoss(String boss) {
		this.boss = boss;
	}

	public BigDecimal getSalery() {
		return this.salery;
	}

	public void setSalery(BigDecimal salery) {
		this.salery = salery;
	}

}
