package com.shopsthai.david.hibernate;

// Generated Nov 14, 2013 10:42:18 PM by Hibernate Tools 3.4.0.CR1

/**
 * Tree generated by hbm2java
 */
public class Tree implements java.io.Serializable {

	private TreeId id;

	public Tree() {
	}

	public Tree(TreeId id) {
		this.id = id;
	}

	public TreeId getId() {
		return this.id;
	}

	public void setId(TreeId id) {
		this.id = id;
	}

}
